FROM webdevops/php-nginx:8.1 as build

# Install apt dependencies
RUN apt-get update && \
    apt-get install -y curl mariadb-client zip unzip dnsutils

# Override Nginx config
RUN rm /etc/nginx/conf.d/10-docker.conf
COPY ./docker-compose/production/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./docker-compose/production/nginx/conf.d /etc/nginx/conf.d

FROM build as production

WORKDIR /app
